### ISSUE TITLE
Can the Adafruit Grand Central board be added to this project?

### ISSUE THREAD

**Issue by BugWhacker** [dmadison/ArduinoXInput_AVR#10]
I am wanting to make an Xbox controller with one. thank you.

**Comment by dmadison** [comment]
Unfortunately not. The Adafruit Grand Central uses a Cortex M4 with SAMD architecture, and cannot use the AVR core.

I do not currently have any plans to redevelop the project for the SAMD architecture. If you'd like to give it a shot yourself, I'd recommend looking through this repository's commit history to see the changes required. I'd also recommend looking at [the ArduinoXInput API documentation in the library repository](https://github.com/dmadison/ArduinoXInput/blob/master/extras/XInputUSB_API.md).
