### ISSUE TITLE
Arduino 2.0.0 "hardware" folder missing?

### ISSUE THREAD

**Issue by baritonomarchetto** [dmadison/ArduinoXInput_AVR#17]
It looks like the new IDE is missing that folder which makes impossible to copy the USB descriptors.

Where should the "xinput" folder go in IDE 2.0.0?

Thanks!

**Comment by dmadison** [comment]
Hi, and thanks for creating this issue.

Both the new (2.0+) and old (1.6+) versions of the IDE make use of an application data folder for installing boards and tools packages. The board files need to go there, within the "packages" folder (and then within some user-created sub-directories). On Windows that folder is located in `%APPDATA%\..\Local\Arduino15`.

The good news is that I've also finally gotten around to creating a "boards" repository and package index, so you can install the XInput boards like any other. Add the package index file to the "Additional Boards Manager URLs" list in the IDE and then install the "XInput AVR Boards" package from the boards manager.

There's more (updated) information in the README. Let me know if you have any questions!
